[package]
name = "cyber_rogue"
version = "0.1.0"
authors = ["Martin Becker <mbeckerwork@gmail.com>"]

[dependencies]
tcod = "0.12"
rand = "0.3.9"
#for ensuring ECS system communication
# ditto = "0.2.0"
